package arima.anotherpack.core;

import arima.anotherpack.blocks.BlocksBarrier;
import arima.anotherpack.blocks.BlocksBox;
import arima.anotherpack.blocks.BlocksCloth;
import arima.anotherpack.blocks.BlocksFire;
import arima.anotherpack.blocks.BlocksGlass;
import arima.anotherpack.blocks.BlocksGrass;
import arima.anotherpack.blocks.BlocksIron;
import arima.anotherpack.blocks.BlocksLadder;
import arima.anotherpack.blocks.BlocksLamp;
import arima.anotherpack.blocks.BlocksLavaFlow;
import arima.anotherpack.blocks.BlocksLavaStill;
import arima.anotherpack.blocks.BlocksLog;
import arima.anotherpack.blocks.BlocksPortal;
import arima.anotherpack.blocks.BlocksRail;
import arima.anotherpack.blocks.BlocksRope;
import arima.anotherpack.blocks.BlocksSnow;
import arima.anotherpack.blocks.BlocksStone;
import arima.anotherpack.blocks.BlocksTorch;
import arima.anotherpack.blocks.BlocksWeb;
import arima.anotherpack.blocks.BlocksWood;
import arima.anotherpack.blocks.FencesStone;
import arima.anotherpack.blocks.FencesWood;
import arima.anotherpack.blocks.SlabsStone;
import arima.anotherpack.blocks.SlabsWood;
import arima.anotherpack.blocks.StairsStone;
import arima.anotherpack.blocks.StairsWood;
import arima.anotherpack.blocks.TestBlocks;
import arima.anotherpack.blocks.VertBlock;
import arima.anotherpack.blocks.WallsStone;
import arima.anotherpack.blocks.WallsWood;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

public class AllBlocks {

	public static Block Snow;
	public static Block Stone;
	public static Block Stonebrick;
	public static Block Wood;
	public static Block Iron;
	public static Block Wood_2_Slab;
	public static Block Wood_3_Slab;
	public static Block Wood_4_Slab;
	public static Block Stone_0_Slab;
	public static Block Stone_1_Slab;
	public static Block Stone_2_Slab;
	public static Block Stone_3_Slab;
	public static Block Stonebrick_0_Slab;
	public static Block Stonebrick_1_Slab;
	public static Block Stonebrick_2_Slab;
	public static Block Stonebrick_3_Slab;
	public static Block Stonebrick_4_Slab;
	public static Block Stonebrick_5_Slab;
	public static Block Stonebrick_6_Slab;
	public static Block Stonebrick_7_Slab;
	public static Block Stonebrick_8_Slab;
	public static Block Stonebrick_9_Slab;
	public static Block Wood_2_Stair;
	public static Block Wood_3_Stair;
	public static Block Wood_4_Stair;
	public static Block Stone_0_Stair;
	public static Block Stone_1_Stair;
	public static Block Stone_2_Stair;
	public static Block Stone_3_Stair;
	public static Block Stonebrick_0_Stair;
	public static Block Stonebrick_1_Stair;
	public static Block Stonebrick_2_Stair;
	public static Block Stonebrick_3_Stair;
	public static Block Stonebrick_4_Stair;
	public static Block Stonebrick_5_Stair;
	public static Block Stonebrick_6_Stair;
	public static Block Stonebrick_7_Stair;
	public static Block Stonebrick_8_Stair;
	public static Block Stonebrick_9_Stair;
	public static Block Wood_Wall;
	public static Block Stone_Wall;
	public static Block Stonebrick_Wall;
	public static Block Wood_2_Fence;
	public static Block Wood_3_Fence;
	public static Block Wood_4_Fence;
	public static Block Stone_0_Fence;
	public static Block Stone_1_Fence;
	public static Block Stone_2_Fence;
	public static Block Stone_3_Fence;
	public static Block Stonebrick_0_Fence;
	public static Block Stonebrick_1_Fence;
	public static Block Stonebrick_2_Fence;
	public static Block Stonebrick_3_Fence;
	public static Block Stonebrick_4_Fence;
	public static Block Stonebrick_5_Fence;
	public static Block Stonebrick_6_Fence;
	public static Block Stonebrick_7_Fence;
	public static Block Stonebrick_8_Fence;
	public static Block Stonebrick_9_Fence;
	public static Block Lamp, Lamp2, Lamp3, Lamp4, Lamp5, Lamp6;
	public static Block Ladder1;
	public static Block Ladder2;
	public static Block Ladder3;
	public static Block Cloth1;
	public static Block Cloth2;
	public static Block Cloth3;
	public static Block cloth_axe, cloth_bita, cloth_shovel, cloth_web;
	public static Block Rope;
	public static Block Grass;
	public static Block Log;
	public static Block Rail1;
	public static Block Rail2;
	public static Block Rail3;
	public static Block Rail4, Rail5, Rail6, Rail7, Rail8, Rail9;
	public static Block Box;
	public static Block Torch1;
	public static Block Torch2;
	public static Block Torch3;
	public static Block Torch4;
	public static Block Torch5;
	public static Block Barrier;
	public static Block MagmaFlow;
	public static Block MagmaStill;
	public static Block Port;
	public static Block Port2;
	public static Block Port3;
	public static Block Web;
	public static Block Fire;
	public static Block Wood2, Wood3, Iron2, Iron3, Iron4;
	public static Block blockDenseAdvMach, blockThaumMach, first_vert, first_gor;
	public static Block Iron_0_Stairs, Iron_1_Stairs;
	public static Block TechBlock, TechBlock2, TechBlockBox_1;
	public static Block Stone2, Stone3, Stone4, Stone5, Stone6;
	public static Block BookShelf, Military, Marble, Marble2, BrazeStone, Bricks, StoneArcane, StoneVoid, BlocksGlass; 
	public static Block BlocksGlass2, BlocksGlass3, IronLabBlock;
	public static Block CarpetBlocks, Futura, PortalBlocks, PortalBlocks2, AnimatedBlocks, AnimatedBlocks2;
	public static Block testBlock = new TestBlocks(Material.rock, "TestBlock", "arima:wood/wood_0");

	public static void registerBlocks() {
		GameRegistry.addShapelessRecipe(new ItemStack(testBlock, 1),
				new Object[] { Blocks.gravel, Items.apple, Blocks.wooden_button, Items.cookie });
		// Гравий, яблоко, деревянная кнопка, печенька
		Snow = new BlocksSnow("Snow", "minecraft:snow");
		Stone = new BlocksStone("Stone", "arima:stone/stone", 16);
		Stone2 = new BlocksStone("Stone2", "arima:stone/stone2", 16);
		Stone3 = new BlocksStone("Stone3", "arima:stone/stone3", 16);
		Stone4 = new BlocksStone("Stone4", "arima:stone/stone4", 16);
		Stone5 = new BlocksStone("Stone5", "arima:stone/stone5", 16);
		Stone6 = new BlocksStone("Stone6", "arima:stone/stone6", 14);
		Stonebrick = new BlocksStone("Stonebrick", "arima:stonebrick/stonebrick", 13);
		Wood = new BlocksWood("Wood", "arima:wood/wood", 16);
		Wood2 = new BlocksWood("Wood2", "arima:wood/wood2", 16);
		Wood3 = new BlocksWood("Wood3", "arima:wood/wood3", 4);
		Iron = new BlocksIron("Iron", "arima:iron/iron", 16);
		Iron2 = new BlocksIron("Iron2", "arima:iron/iron2", 16);
		Iron3 = new BlocksIron("Iron3", "arima:iron/iron3", 16);
		Wood_2_Slab = new SlabsWood("Wood_Slab", "arima:wood/wood_2");
		Wood_3_Slab = new SlabsWood("Wood_3_Slab", "arima:wood/wood_3");
		Wood_4_Slab = new SlabsWood("Wood_4_Slab", "arima:wood/wood_4");
		Stone_0_Slab = new SlabsStone("Stone_0_Slab", "arima:stone/stone_0");
		Stone_1_Slab = new SlabsStone("Stone_1_Slab", "arima:stone/stone_1");
		Stone_2_Slab = new SlabsStone("Stone_2_Slab", "arima:stone/stone_2");
		Stone_3_Slab = new SlabsStone("Stone_3_Slab", "arima:stone/stone_3");
		Stonebrick_0_Slab = new SlabsStone("Stonebrick_0_Slab", "arima:stonebrick/stonebrick_0");
		Stonebrick_1_Slab = new SlabsStone("Stonebrick_1_Slab", "arima:stonebrick/stonebrick_1");
		Stonebrick_2_Slab = new SlabsStone("Stonebrick_2_Slab", "arima:stonebrick/stonebrick_2");
		Stonebrick_3_Slab = new SlabsStone("Stonebrick_3_Slab", "arima:stonebrick/stonebrick_3");
		Stonebrick_4_Slab = new SlabsStone("Stonebrick_4_Slab", "arima:stonebrick/stonebrick_4");
		Stonebrick_5_Slab = new SlabsStone("Stonebrick_5_Slab", "arima:stonebrick/stonebrick_5");
		Stonebrick_6_Slab = new SlabsStone("Stonebrick_6_Slab", "arima:stonebrick/stonebrick_6");
		Stonebrick_7_Slab = new SlabsStone("Stonebrick_7_Slab", "arima:stonebrick/stonebrick_7");
		Stonebrick_8_Slab = new SlabsStone("Stonebrick_8_Slab", "arima:stonebrick/stonebrick_8");
		Stonebrick_9_Slab = new SlabsStone("Stonebrick_9_Slab", "arima:stonebrick/stonebrick_9");
		Wood_2_Stair = new StairsWood("Wood_2_Stair", Wood, 2);
		Wood_3_Stair = new StairsWood("Wood_3_Stair", Wood, 3);
		Wood_4_Stair = new StairsWood("Wood_4_Stair", Wood, 4);
		Stone_0_Stair = new StairsStone("Stone_0_Stair", Stone, 0);
		Stone_1_Stair = new StairsStone("Stone_1_Stair", Stone, 1);
		Stone_2_Stair = new StairsStone("Stone_2_Stair", Stone, 2);
		Stone_3_Stair = new StairsStone("Stone_3_Stair", Stone, 3);
		Stonebrick_0_Stair = new StairsStone("Stonebrick_0_Stair", Stonebrick, 0);
		Stonebrick_1_Stair = new StairsStone("Stonebrick_1_Stair", Stonebrick, 1);
		Stonebrick_2_Stair = new StairsStone("Stonebrick_2_Stair", Stonebrick, 2);
		Stonebrick_3_Stair = new StairsStone("Stonebrick_3_Stair", Stonebrick, 3);
		Stonebrick_4_Stair = new StairsStone("Stonebrick_4_Stair", Stonebrick, 4);
		Stonebrick_5_Stair = new StairsStone("Stonebrick_5_Stair", Stonebrick, 5);
		Stonebrick_6_Stair = new StairsStone("Stonebrick_6_Stair", Stonebrick, 6);
		Stonebrick_7_Stair = new StairsStone("Stonebrick_7_Stair", Stonebrick, 7);
		Stonebrick_8_Stair = new StairsStone("Stonebrick_8_Stair", Stonebrick, 8);
		Stonebrick_9_Stair = new StairsStone("Stonebrick_9_Stair", Stonebrick, 9);
		Wood_Wall = new WallsWood("Wood_Wall", "arima:wood/wood", 11);
		Stone_Wall = new WallsStone("Stone_Wall", "arima:stone/stone", 9);
		Stonebrick_Wall = new WallsStone("Stonebrick_Wall", "arima:stonebrick/stonebrick", 12);
		Wood_2_Fence = new FencesWood("Wood_Fence", "arima:wood/wood_2");
		Wood_3_Fence = new FencesWood("Wood_3_Fence", "arima:wood/wood_3");
		Wood_4_Fence = new FencesWood("Wood_4_Fence", "arima:wood/wood_4");
		Stone_0_Fence = new FencesStone("Stone_0_Fence", "arima:stone/stone_0");
		Stone_1_Fence = new FencesStone("Stone_1_Fence", "arima:stone/stone_1");
		Stone_2_Fence = new FencesStone("Stone_2_Fence", "arima:stone/stone_2");
		Stone_3_Fence = new FencesStone("Stone_3_Fence", "arima:stone/stone_3");
		Iron_0_Stairs = new StairsStone("Iron_0_Stairs", Iron, 0).setCreativeTab(Main.tabAPIronBlocks);
		Iron_1_Stairs = new StairsStone("Iron_1_Stairs", Iron, 1).setCreativeTab(Main.tabAPIronBlocks);
		Stonebrick_0_Fence = new FencesStone("Stonebrick_0_Fence", "arima:stonebrick/stonebrick_0");
		Stonebrick_1_Fence = new FencesStone("Stonebrick_1_Fence", "arima:stonebrick/stonebrick_1");
		Stonebrick_2_Fence = new FencesStone("Stonebrick_2_Fence", "arima:stonebrick/stonebrick_2");
		Stonebrick_3_Fence = new FencesStone("Stonebrick_3_Fence", "arima:stonebrick/stonebrick_3");
		Stonebrick_4_Fence = new FencesStone("Stonebrick_4_Fence", "arima:stonebrick/stonebrick_4");
		Stonebrick_5_Fence = new FencesStone("Stonebrick_5_Fence", "arima:stonebrick/stonebrick_5");
		Stonebrick_6_Fence = new FencesStone("Stonebrick_6_Fence", "arima:stonebrick/stonebrick_6");
		Stonebrick_7_Fence = new FencesStone("Stonebrick_7_Fence", "arima:stonebrick/stonebrick_7");
		Stonebrick_8_Fence = new FencesStone("Stonebrick_8_Fence", "arima:stonebrick/stonebrick_8");
		Stonebrick_9_Fence = new FencesStone("Stonebrick_9_Fence", "arima:stonebrick/stonebrick_9");
		Lamp = new BlocksLamp("Lamp", "arima:lamp/lamp", 16);
		Ladder1 = new BlocksLadder("Ladder1", "arima:ladder/ladder_0");
		Ladder2 = new BlocksLadder("Ladder2", "arima:ladder/ladder_1");
		Ladder3 = new BlocksLadder("Ladder3", "arima:ladder/ladder_2");
		Cloth1 = new BlocksCloth("Cloth1", "arima:cloth/cloth_0");
		Cloth2 = new BlocksCloth("Cloth2", "arima:cloth/cloth_1");
		Cloth3 = new BlocksCloth("Cloth3", "arima:cloth/cloth_2");
		cloth_axe = new BlocksCloth("cloth_axe", "arima:cloth/cloth_axe");
		cloth_bita = new BlocksCloth("cloth_bita", "arima:cloth/cloth_bita");
		cloth_shovel = new BlocksCloth("cloth_shovel", "arima:cloth/cloth_shovel");
		cloth_web = new BlocksCloth("cloth_web", "arima:cloth/cloth_web");
		Rope = new BlocksRope("Rope", "arima:rope/rope", 11);
		Grass = new BlocksGrass("Grass", "arima:grass/grass", 4);
		Rail1 = new BlocksRail("Rail1", "arima:rail/rail_0");
		Rail2 = new BlocksRail("Rail2", "arima:rail/rail_1");
		Rail3 = new BlocksRail("Rail3", "arima:rail/rail_2");
		Rail4 = new BlocksRail("Rail4", "arima:rail/rail_3");
		Rail5 = new BlocksRail("Rail5", "arima:rail/rail_break_glass");
		Rail6 = new BlocksRail("Rail6", "arima:rail/rail_charcoal");
		Rail7 = new BlocksRail("Rail7", "arima:rail/rail_leather");
		Rail8 = new BlocksRail("Rail8", "arima:rail/rail_paper");
		Rail9 = new BlocksRail("Rail9", "arima:rail/rail_paper_2");
		Log = new BlocksLog("Log", "arima:log/log", 3);
		Box = new BlocksBox("Barrel", "arima:box/box", 15);
		Torch1 = new BlocksTorch("Torch1", "arima:torch/torch_0");
		Torch2 = new BlocksTorch("Torch2", "arima:torch/torch_1");
		Torch3 = new BlocksTorch("Torch3", "arima:torch/torch_2");
		Torch4 = new BlocksTorch("Torch4", "arima:torch/torch_3");
		Torch5 = new BlocksTorch("Torch5", "arima:torch/torch_4");
		Web = new BlocksWeb("Web", "arima:web/web");
		Fire = new BlocksFire("Fire", "arima:fire/fire");
		Barrier = new BlocksBarrier("Barrier", "arima:barrier/barrier");
		MagmaFlow = new BlocksLavaFlow("MagmaFlow");
		MagmaStill = new BlocksLavaStill("MagmaStill");
		blockDenseAdvMach = new BlocksIron("blockDenseAdvMach", "arima:n6/blockDenseAdvMach", 1);
		blockThaumMach = new BlocksIron("blockThaumMach", "arima:n6/blockThaumMach", 1);
		first_vert = new VertBlock("first_vert", "arima:dv_vert/fv");
		first_gor = new VertBlock("first_gor", "arima:dv_vert/fg");
		TechBlockBox_1 = new BlocksBox("TechBlockBox_1", "arima:TechBlock/TechBlockBox_1", 1).setCreativeTab(Main.tabAPIronBlocks);
		TechBlock = new BlocksIron("TechBlock", "arima:TechBlock/TechBlock", 16);
		TechBlock2 = new BlocksIron("TechBlock2", "arima:TechBlock/TechBlock2", 13);
		BookShelf = new BlocksBox("BookShelf", "arima:box/BookShelf", 8);
		Military = new BlocksIron("Military", "arima:iron/Military", 5);
		IronLabBlock = new BlocksIron("IronLabBlock", "arima:iron/Lab", 3);
		Marble = new BlocksStone("Marble", "arima:stone/Marble", 16);
		Marble2 = new BlocksStone("Marble2", "arima:stone/Marble2", 2);
		BrazeStone = new BlocksStone("Braze", "arima:stone/Braze", 10);
		Bricks = new BlocksStone("Bricks", "arima:stonebrick/Brick", 13);
		StoneArcane = new BlocksStone("StoneArcane", "arima:Arcane/Arcane", 5);
		Lamp2 = new BlocksLamp("Lamp2", "arima:lamp/Lamp2", 16);
		Lamp3 = new BlocksLamp("Lamp3", "arima:lamp/Lamp3", 16);
		Lamp4 = new BlocksLamp("Lamp4", "arima:lamp/Lamp4", 16);
		Lamp5 = new BlocksLamp("Lamp5", "arima:lamp/Lamp5", 16);
		Lamp6 = new BlocksLamp("Lamp6", "arima:lamp/Lamp6", 2);
		StoneVoid = new BlocksStone("StoneVoid", "arima:stone/Void", 6);
		BlocksGlass = new BlocksGlass("BlocksGlass", "arima:Glass/Glass", 16);
		BlocksGlass2 = new BlocksGlass("BlocksGlass2", "arima:Glass/Glass2", 16);
		BlocksGlass3 = new BlocksGlass("BlocksGlass3", "arima:Glass/Glass3", 12);
		CarpetBlocks = new BlocksStone("CarpetBlocks", "arima:Carpet/Carpet", 16).setCreativeTab(Main.tabAP2DesignBlocks);
		Futura = new BlocksIron("Futura", "arima:iron/Futura", 3);
		PortalBlocks = new BlocksPortal("PortalBlocks", "arima:Portals/Portal", 16);
		PortalBlocks2 = new BlocksPortal("PortalBlocks2", "arima:Portals/Portal2", 7);
		AnimatedBlocks = new BlocksStone("AnimatedBlocks", "arima:AnimatedBlock/Animated", 16).setCreativeTab(Main.tabAP2DesignBlocks);
		AnimatedBlocks2 = new BlocksStone("AnimatedBlocks2", "arima:AnimatedBlock/Animated2", 6).setCreativeTab(Main.tabAP2DesignBlocks);
	}
}
